{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1761234740302, "stop": 1761234741714}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1761234741714, "stop": 1761234744785}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1761234744786, "stop": 1761234744786}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1761234740302, "stop": 1761234744786, "uuid": "19a1349f-6821-47c3-8c49-de82b27e4b97", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизаци"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-FHO9UBL"}, {"name": "thread", "value": "14432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}